### ISSUE TITLE
Sentence boundaries unset

### ISSUE THREAD

**Issue by vistamou** [BramVanroy/spacy_conll#17]
Hello,

I have trained a transformer model only for morphologizer and tagger (no sentencizer included) and I wanted to tag
my data--but I get the following error:

ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: `nlp.add_pipe('sentencizer')`. Alternatively, add the dependency parser or sentence recognizer, or set sentence boundaries by setting `doc[i].is_sent_start`.

any idea of how can I bypass this?

Thank you!!

**Comment by BramVanroy** [comment]
Hi @vistamou, can you post the code that you used and the full error trace that you get?

**Comment by vistamou** [comment]
yes, I'm running the following:

`parse-as-conll model-best/ spacy --input_file test.txt --output_file output.txt`

Traceback (most recent call last):
  File "/home/../parse-as-conll", line 8, in <module>
    sys.exit(main())
  File "/home/../spacy_conll/cli/parse.py", line 175, in main
    parse(cargs)
  File "/home/../spacy_conll/cli/parse.py", line 32, in parse
    no_split_on_newline=args.no_split_on_newline,
  File "/home/../spacy_conll/parser.py", line 85, in parse_file_as_conll
    return self.parse_text_as_conll(text, **kwargs)
  File "/home/../parser.py", line 135, in parse_text_as_conll
    for doc_idx, doc in enumerate(self.nlp.pipe(text, n_process=n_process)):
  File "/home/vivs/spaCy/spacy/language.py", line 1578, in pipe
    for doc in docs:
  File "/home/vivs/spaCy/spacy/util.py", line 1614, in _pipe
    error_handler(name, proc, [doc], e)
  File "/home/vivs/spaCy/spacy/util.py", line 1618, in raise_error
    raise e
  File "/home/vivs/spaCy/spacy/util.py", line 1611, in _pipe
    doc = proc(doc, **kwargs)  # type: ignore[call-arg]
  File "/home/../spacy_conll/formatter.py", line 108, in __call__
    for sent_idx, sent in enumerate(doc.sents, 1):
  File "spacy/tokens/doc.pyx", line 873, in sents
ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: `nlp.add_pipe('sentencizer')`. Alternatively, add the dependency parser or sentence recognizer, or set sentence boundaries by setting `doc[i].is_sent_start`

**Comment by BramVanroy** [comment]
Does the same problem occur when you use `--disable_sbd`? This will disable automatic sentence segmentation, but considering that you have no parser or sentencizer anyway, that should not make a difference.
```python
parse-as-conll model-best/ spacy --input_file test.txt --output_file output.txt --disable_sbd
```

**Comment by vistamou** [comment]
yes exactly, I get:

`ValueError: [E001] No component 'parser' found in pipeline. Available names: ['transformer', 'morphologizer', 'tagger', 'attribute_ruler']`

**Comment by BramVanroy** [comment]
Again, please include the full error trace.

**Comment by vistamou** [comment]
ok, yes sorry:

```
Traceback (most recent call last):
  File "/home/../parse-as-conll", line 8, in <module>
    sys.exit(main())
  File "/home/../spacy_conll/cli/parse.py", line 175, in main
    parse(cargs)
  File "/home/vivs/../spacy_conll/cli/parse.py", line 20, in parse
    include_headers=args.include_headers,
  File "/home/vivs/../spacy_conll/utils.py", line 65, in init_parser
    nlp.add_pipe("disable_sbd", before="parser")
  File "/home/vivs/spaCy/spacy/language.py", line 795, in add_pipe
    pipe_index = self._get_pipe_index(before, after, first, last)
  File "/home/vivs/spaCy/spacy/language.py", line 828, in _get_pipe_index
    Errors.E001.format(name=before, opts=self.component_names)
ValueError: [E001] No component 'parser' found in pipeline. Available names: ['transformer', 'morphologizer', 'tagger', 'attribute_ruler']

```

**Comment by BramVanroy** [comment]
Hm, okay this is an edge case that I had not considered. The solution would be to check which of these components are available (parser, senter, sentencizer), and place disable_sbd before the first of those. As a fallback - because you have none of those - it can be placed first in the pipeline.

I can only implement this in February though, but a PR is welcome!

**Comment by vistamou** [comment]
aha, ok! Thanks a lot :)

**Comment by BramVanroy** [comment]
Hi vistamou, can you try to install commit 31d4f64 and see if that solves your issue?

```
pip install git+git://github.com/BramVanroy/spacy_conll.git@31d4f647150b46ff9b3028ccfef6704dc879beff
```
