### ISSUE TITLE
command line example is not working

### ISSUE THREAD

**Issue by arademaker** [BramVanroy/spacy_conll#3]
```
% python -m spacy_conll -h
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/ar/.env/lib/python3.7/site-packages/spacy_conll/__main__.py", line 7, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

**Comment by BramVanroy** [comment]
You have to install the packaging module. 

 ```bash
pip install packaging
```
