### ISSUE TITLE
TypeError: ConllParser.__init__() got an unexpected keyword argument 'is_tokenized' when using command parse-as-conll

### ISSUE THREAD

**Issue by fishfree** [BramVanroy/spacy_conll#30]
Whether I use -t argument or not.
```
(spacy) mememe@ubuntugpu:~$ parse-as-conll en_core_web_sm spacy --input_str "I like cookies. What about you?" -t --include_headers
Traceback (most recent call last):
  File "/mnt/data/mememe/.local/bin/parse-as-conll", line 8, in <module>
    sys.exit(main())
  File "/mnt/data/mememe/.local/lib/python3.10/site-packages/spacy_conll/cli/parse.py", line 175, in main
    parse(cargs)
  File "/mnt/data/mememe/.local/lib/python3.10/site-packages/spacy_conll/cli/parse.py", line 23, in parse
    parser = ConllParser(nlp, is_tokenized=args.is_tokenized)
TypeError: ConllParser.__init__() got an unexpected keyword argument 'is_tokenized'
```

I have to change line 23 to "parser = ConllParser(nlp)".

**Comment by kleag** [comment]
I confirm. I encountered the same problem.
